services:
  main-db:
    image: postgres:16.1
    container_name: postgres-main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    build: ./core/main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - SPRING_CLOUD_CONFIG_ENABLED=false
      - EUREKA_CLIENT_ENABLED=false