server.port=8080
spring.application.name=gateway-server

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ???????? ? main-service
spring.cloud.gateway.routes[0].id=main-service-public
spring.cloud.gateway.routes[0].uri=lb://main-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/categories/**,/events/**,/compilations/**,/comments/**

spring.cloud.gateway.routes[1].id=main-service-admin
spring.cloud.gateway.routes[1].uri=lb://main-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/admin/**

spring.cloud.gateway.routes[2].id=main-service-users
spring.cloud.gateway.routes[2].uri=lb://main-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/users/**